// Generated by CoffeeScript 1.6.3
(function() {
  var dataClass, root;

  dataClass = (function() {
    function dataClass(fireurl) {
      this.fireurl = fireurl;
      this.dataRef = new Firebase(this.fireurl);
    }

    dataClass.prototype.addPost = function(postObject) {
      var childref;
      childref = this.dataRef.child(postObject.key);
      return childref.set(postObject);
    };

    dataClass.prototype.getPost = function(key) {
      return this.dataRef.child(key);
    };

    dataClass.prototype.removePost = function(key) {
      var ref;
      ref = new Firebase(this.fireurl(+'/' + key));
      return ref.remove();
    };

    return dataClass;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.dataClass = dataClass;

}).call(this);

/*
//@ sourceMappingURL=boardData.map
*/
