// Generated by CoffeeScript 1.6.3
(function() {
  var $;

  $ = jQuery;

  $(function() {
    $("#listing").postViewer();
    $("#form").postForm();
    return $("#authentication").auth();
  });

}).call(this);

/*
//@ sourceMappingURL=interaction.map
*/
