// Generated by CoffeeScript 1.6.3
(function() {
  var $,
    _this = this;

  $ = jQuery;

  $.widget("fbBoard.postForm", {
    _init: function() {
      return this.firebase = new dataClass('https://board.firebaseio.com');
    },
    _create: function() {
      var formHTML;
      this.element.addClass("postForm");
      formHTML = "<div>" + "<form>" + "<table>" + "<tr><td><span>Url : </span></td><td><input id='postURL' type='url' placeholder='Enter URL..' required></td></tr>" + "<tr><td><span>Description : </span></td><td><textarea id='postDescription' rows='3' cols='17' placeholder='Enter Description..' /></td></tr>" + "<tr><td colspan='2'><input id='submitButton' type='submit' value='Post'></td></tr>" + "</table>" + "</form>" + "</div>";
      this.element.html(formHTML);
      return this.element.find('#submitButton').on('click', {
        context: this
      }, this._triggerClick);
    },
    _triggerClick: function(event) {
      var descVal, urlVal;
      event.preventDefault();
      event.stopPropagation();
      if ($('#postURL')[0].checkValidity()) {
        urlVal = $(event.target.form.postURL).val();
        descVal = $(event.target.form.postDescription).val();
        return event.data.context.firebase.addPost({
          key: event.data.context._escapeSpecialCharacters(urlVal),
          url: urlVal,
          description: descVal,
          user: $("#authentication").auth('GetCurrentUser')
        });
      }
    },
    _escapeSpecialCharacters: function(string) {
      if (!string) {
        return false;
      }
      string = string.toLowerCase();
      return string = string.replace(/\./g, ',').replace(/\//g, ',');
    }
  });

}).call(this);

/*
//@ sourceMappingURL=postEntryWidget.map
*/
